### ISSUE TITLE
Slash - Action with no href has a black icon

### ISSUE THREAD

**Issue by JLou** [AxaFrance/design-system#604]
When using the `Action` component without a href, the icon is black instead of white or blue on hover.
On the left, the toolkit component, on the right the design-system-slash-react component:

![image](https://github.com/user-attachments/assets/9fbaf190-fe82-4d47-b016-d985d19a0295)
![image](https://github.com/user-attachments/assets/b4001dc5-4692-4b03-b1e0-010f03d225f4)

Reproduction: 
```tsx
      <Action icon="plus" onClick={() => console.log("hello")} />
```

The culprit is in the reboot css: 

```css
a:not([href], [tabindex]) {
  text-decoration: none;
  color: inherit;
}
```
